### ISSUE TITLE
Service workers is missing, only service workers v1 is present

### ISSUE THREAD

**Issue by domenic** [tobie/specref#308]
That is, the URL https://w3c.github.io/ServiceWorker/ does not appear in the database at all, only https://w3c.github.io/ServiceWorker/v1 and some TR counterparts. Seems bad...

**Comment by tobie** [comment]
Mmm. Per-level EDs?

**Comment by domenic** [comment]
I guess so :(

**Comment by tobie** [comment]
@jungkees, @jakearchibald, @slightlyoff: what's the difference between your V1 and Nightly ED? Which one should we use? Also what *is* a Nightly ED?

**Comment by jungkees** [comment]
https://w3c.github.io/ServiceWorker/v1 is an ED branch for Service Workers 1 spec that we're moving to REC. Nightly is basically a living branch. We're trying to publish a FPWD of Service Workers 2 (that has new WIP features such as foreign fetch, navigation preload, link type "serviceworker", and so on) soon too.

@tobie, I was not familiar with this project but found bikeshed is already using this API. IMO, other specs except W3C CR/PR/REC documents have to reference the dfns in https://w3c.github.io/ServiceWorker/ instead of https://w3c.github.io/ServiceWorker/v1. Is there any way I can make https://w3c.github.io/ServiceWorker/ appear in the database?

**Comment by tobie** [comment]
Thanks for the explanation @jungkees. Will fix manually here. Addressed the more general issue on spec-prod@: https://lists.w3.org/Archives/Public/spec-prod/2016OctDec/0015.html. W3C needs to define a structure for this imho. Currently it's a mess.
