### ISSUE TITLE
WebIDL-1 reported as WD

### ISSUE THREAD

**Issue by dontcallmedom** [tobie/specref#321]
WebIDL-1 was published as a Rec, but specref reports it as Rec - raising this as an issue since there is probably a problem in the synchronization with TR data.

**Comment by tobie** [comment]
Yeah, WebIDL-1 redirects to WebIDL as of https://github.com/tobie/specref/commit/ee2359a73615fa96faafee17a79aab1b58a08aa8.

This is tied to the conversation about leveled specs lead by @deniak.

What's the use-case for linking to WebIDL-1?

**Comment by tidoust** [comment]
There seems to be two issues in one.

The first issue is that the status reported by specref for WebIDL is incorrect: Specref says the document published on 15 December 2016 at https://www.w3.org/TR/WebIDL-1/ is a WD, whereas it is a REC. Shouldn't [WebIDL] report the same info as [WebIDL-20161215], the latest published spec?
http://www.specref.org/?q=webidl-20161215

The second issue is the ability to specifically link to WebIDL-1 or WebIDL-2 instead of just WebIDL. Two use cases come to mind for specs that are to be published as PR/REC:

1. Linking to WebIDL-1 to assert that all IDL concepts used in the spec are stable to ease Director's transitions.
2. Linking to WebIDL-2 to point out specific terms that are not yet "stable".

One concrete example: the [Presentation API](http://w3c.github.io/presentation-api/) uses `NotAllowedError`, which is defined in WebIDL Level 2. I'd like some way to say somethink like "all IDL terms are defined in [WebIDL-1], except `NotAllowedError`, defined in [WebIDL-2]". Or "all IDL terms are defined in [WebIDL]. At the time of publication, `NotAllowedError` is defined in the ED of [WebIDL-2] and considered stable".

My understanding is that the leveled spec proposals could make "/TR/webIDL/" link to the latest level (i.e. the Level 2 WD here, once published), but "/TR/webIDL-1" would still point to "WebIDL Level 1".

@deniak, proposals do not seem to say anything about which shortname PR/REC specs should use for references. What is the expectation?

**Comment by deniak** [comment]
Just to clarify, [the current proposal](https://w3c.github.io/tr-links/versioning/) actually has 3 options and we haven't decided yet whether /TR/shortname should point to the latest level or the most stable version.

Regarding WebIDL, I think there's a small problem. I confirmed with @ylafon and at some point, there was a shortname change from webidl to webidl-1 (see [WebIDL-1 history](https://www.w3.org/standards/history/WebIDL-1)) so technically, /TR/WebIDL should point to /TR/WebIDL-1. If we agree on this, I will fix the error.

**Comment by tobie** [comment]
@deniak this is precisely why it's key to come up with a consistant story for spec levels and enforce it. Levels should be tags in Git parlance (branches when you need to run things in parallel for a little while). WD's and the like should just be tags along the way.

There _is_ something weird going on with WebIDL, though, as `/TR/WebIDL-1` points to the December 15, 2016 Rec, and `/TR/WebIDL` points to the April 19, 2012 CR.

On the Specref side, I'm experimenting with treating WebIDL as a "leveled" spec. Every version is stored under the WebIDL shortname, and WebIDL-1 points to WebIDL-20161215.

**Comment by deniak** [comment]
@tobie it should now be fixed. As per @ylafon's request, /TR/WebIDL now redirects (HTTP 307) to /TR/WebIDL-1

**Comment by ylafon** [comment]
Note that it was a request from the chairs until we figure out what to do with /TR/WebIDL (and have the edcopy published as WDs).
Note the use of a temporary redirect so that we can change what it redirects to (i.e.: no hard choices were made)
