### ISSUE TITLE
Add current service workers draft

### ISSUE THREAD

**Issue by domenic** [tobie/specref#445]
https://w3c.github.io/ServiceWorker/ is not in the database. Ideally [SERVICE-WORKERS] should go there, not to the v1 snapshot.

**Comment by tobie** [comment]
So this was fixed in https://github.com/tobie/specref/commit/ab8104837a9e08e5f22e42fe1030b13d83dfe8c2, following https://github.com/tobie/specref/issues/308. Then was removed in https://github.com/tobie/specref/commit/8156b3fdc311cb1c3d659a0baad23402c5323d69 as it had been fixed on the W3C side. Only to be broken again with the next release of the WD automatically merged in https://github.com/tobie/specref/commit/945fc5d4d7542be616dbbc79466df559f83a123f. I guess I'm going to leave the fix in.

**Comment by tobie** [comment]
So the fix can take up to an hour for the bot to kick in.
