### ISSUE TITLE
Querying both dependencies and dependents

### ISSUE THREAD

**Issue by elf-pavlik** [tobie/specref#751]
To illustrate it I will use an example of an npm package

![image](https://github.com/tobie/specref/assets/876431/7d2b721e-68dd-440a-a9d0-9e14c57982ae)

Given a package, one can find both its dependencies and dependants.  I would find it very useful if https://www.specref.org/ provided similar functionality for specs. Preferably it would be available both using the website and JSON API.

**Comment by tobie** [comment]
Agreed. That would require substantial work to enable, however.

Reffy (https://github.com/tidoust/reffy-service) maintained by @tidoust does this already, at leas for W3C specs.

**Comment by elf-pavlik** [comment]
Thank you! Do you think there would be an interest in improving integration between webref /reffy and specref?

Besides the potential for creating smooth experiences when navigating various specs and their dependencies. It could also come useful for [Advancement on the Recommendation Track](https://www.w3.org/2023/Process-20230612/#transition-reqs).
Actually, the maturity of normative dependencies came up in the process of writing the proposed Solid WG charter https://github.com/solid/solid-wg-charter/issues/37#issuecomment-1567038721. Given that some drafts depend on other drafts, normative references need to be considered already when CG intends to submit some of its drafts to planned WG.

**Comment by tidoust** [comment]
> Thank you! Do you think there would be an interest in improving integration between webref /reffy and specref?

I note that the list of specs and the info you'll find in browser-specs should be aligned with Specref: info in browser-specs either comes from the same sources that feed Specref or from Specref itself (or directly from the specs but in such cases browser-specs contributes back the info to Specref). In short, Specref is a superset of browser-specs. There may be slight differences in some of the spec URLs or spec shortnames, often due to historical reasons, but that should remain an exception to the rule.

Specs that are in Specref but not in browser-specs cannot easily be added to browser-specs because such specs typically follow a different format (e.g., PDF) or structure (different tags and class names to identify blocks of interest). Reffy would in particular not be able to extract the list of references that these specs contain. In other words, you wouldn't get the info you're looking for in Webref for these specs even if they were added to browser-specs.

Further integration could still be useful, e.g. by creating some sort of query endpoint that also looks into Webref data. Not sure where that should live and who could maintain that ;)

> Besides the potential for creating smooth experiences when navigating various specs and their dependencies. It could also come useful for [Advancement on the Recommendation Track](https://www.w3.org/2023/Process-20230612/#transition-reqs).
> Actually, the maturity of normative dependencies came up in the process of writing the proposed Solid WG charter https://github.com/solid/solid-wg-charter/issues/37#issuecomment-1567038721. Given that some drafts depend on other drafts, normative references need to be considered already when CG intends to submit some of its drafts to planned WG.

For this particular use case, I'm not sure tooling can do more than separate normative references into two buckets: "fine" or "need to be checked" as the evaluation of whether a normative reference is or will be fine remains a judgment call in practice. It seems already relatively easy to come up with these two lists simply by looking at the list of normative references in a spec. Or am I missing something?

**Comment by elf-pavlik** [comment]
I think the main feature that I currently look for is to find what depends on the given spec. [webref-analysis](https://w3c.github.io/webref-analysis/) gives a nice example of what is already available.

Thank you both!
